### ISSUE TITLE
Farming dependecy

### ISSUE THREAD

**Issue by daretmavi** [berengma/water_life#47] opened 2020-11-20 00:11 UTC
Farming mode is now a mandatory dependency.
```

2020-11-20 01:10:16: WARNING[Main]: Undeclared global variable "farming" accessed at /home/user/.minetest/mods/water_life/crafts.lua:96
2020-11-20 01:10:16: ERROR[Main]: ModError: Failed to load and run script from /home/user/.minetest/mods/water_life/init.lua:
2020-11-20 01:10:16: ERROR[Main]: /home/user/.minetest/mods/water_life/crafts.lua:96: attempt to index global 'farming' (a nil value)
2020-11-20 01:10:16: ERROR[Main]: stack traceback:
2020-11-20 01:10:16: ERROR[Main]: 	/home/user/.minetest/mods/water_life/crafts.lua:96: in main chunk
2020-11-20 01:10:16: ERROR[Main]: 	[C]: in function 'dofile'
2020-11-20 01:10:16: ERROR[Main]: 	/home/user/.minetest/mods/water_life/init.lua:41: in main chunk
```

**Comment by berengma** [comment] 2020-11-21 12:40
I can't reproduce this error.

**Comment by daretmavi** [comment] 2020-11-21 19:18
Do you test in with default Minetestgame from Minetest 5.3 and this mod only?
If I add farming to optional, the it works.

Try to run it from "Development test" and default mod, then it forced flowers, but with default+flowers it works.
(flowers is dependency as well)

I tried to add `minetest.log(dump(farming))` on line 96 and got similar warning in debug.txt:
`WARNING[Main]: Undeclared global variable "farming" accessed at /home/daret/.minetest/mods/water_life/crafts.lua:96`

**Comment by daretmavi** [comment] 2020-11-22 10:13
"fireflies" mod seems to be dependency as well, because of "bug_net"

**Comment by berengma** [comment] 2020-11-22 12:42
now I could reproduce.
If you add unified_inventory to your mod selection the crash will not happen.
Without unified_inventory, game will crash stating the error you mentioned.

missing dependencies will be added.

**Comment by berengma** [comment] 2020-11-22 12:58
fixed by now. closing

**Closed by berengma** 2020-11-22 12:58 UTC
Labels: willbeworkedon
