### ISSUE TITLE
vector.lua:67: attempt to index local 'pos2' (a nil value)

### ISSUE THREAD

**Issue by Bastrabun** [berengma/water_life#80] opened 2021-08-18 18:28 UTC
Server crash for no apparent reason. 

```
2021-08-18 20:18:20: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'water_life' in callback luaentity_Step(): ...ve1/5.4.1/Minetest_live/bin/../builtin/common/vector.lua:67: attempt to index local 'pos2' (a nil value)
2021-08-18 20:18:20: ERROR[Main]: stack traceback:
2021-08-18 20:18:20: ERROR[Main]: 	...ve1/5.4.1/Minetest_live/bin/../builtin/common/vector.lua:67: in function 'direction'
2021-08-18 20:18:20: ERROR[Main]: 	/home/mtlive1/.minetest/mods/water_life/api.lua:447: in function 'get_yaw_to_object'
2021-08-18 20:18:20: ERROR[Main]: 	/home/mtlive1/.minetest/mods/water_life/behaviors.lua:1222: in function 'func'
2021-08-18 20:18:20: ERROR[Main]: 	/home/mtlive1/.minetest/mods/mobkit/init.lua:621: in function 'execute_queues'
2021-08-18 20:18:20: ERROR[Main]: 	/home/mtlive1/.minetest/mods/mobkit/init.lua:848: in function 'func'
2021-08-18 20:18:20: ERROR[Main]: 	...inetest_live/bin/../builtin/profiler/instrumentation.lua:106: in function <...inetest_live/bin/../builtin/profiler/instrumentation.lua:100>

```

**Comment by berengma** [comment] 2021-08-21 18:03
just another missing nil check I guess. Is it happen frequently ?

**Comment by Bastrabun** [comment] 2021-08-27 23:23
I'd have to go through logs to see how often missing nil checks in water_life crashes us the server. Ofc, it's much more often than I wish for, but it's much less often than what I expect from a missing nil check. So must be rare circumstances. If you want me to add debug stuff for a while to see what's really going on, why those values are actually nil, I'll gladly do :)

**Comment by berengma** [comment] 2021-08-28 06:23
Thanks but I do not think I need some debug. I am pretty sure it is a missing nil check. Frequency usually depends on server lag an d number of players. Like on my own server there is like 0 lag but also almost 0 players :D So this did not happen even a single time. This is a minetest engine problem, when modding you need to check for nil at every each and then.

**Comment by Bastrabun** [comment] 2021-08-29 02:47
If you want me to keep count, I can do so. On my server, it happened again today, the stacktrace doesn't read much different.

```
2021-08-29 02:49:00: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'water_life' in callback luaentity_Step(): ...ve1/5.4.1/Minetest_live/bin/../builtin/common/vector.lua:67: attempt to index local 'pos2' (a nil value)
2021-08-29 02:49:00: ERROR[Main]: stack traceback:
2021-08-29 02:49:00: ERROR[Main]: 	...ve1/5.4.1/Minetest_live/bin/../builtin/common/vector.lua:67: in function 'direction'
2021-08-29 02:49:00: ERROR[Main]: 	/home/mtlive1/.minetest/mods/water_life/api.lua:447: in function 'get_yaw_to_object'
2021-08-29 02:49:00: ERROR[Main]: 	/home/mtlive1/.minetest/mods/water_life/behaviors.lua:1222: in function 'func'
2021-08-29 02:49:00: ERROR[Main]: 	/home/mtlive1/.minetest/mods/mobkit/init.lua:621: in function 'execute_queues'
2021-08-29 02:49:00: ERROR[Main]: 	/home/mtlive1/.minetest/mods/mobkit/init.lua:848: in function 'func'
2021-08-29 02:49:00: ERROR[Main]: 	...inetest_live/bin/../builtin/profiler/instrumentation.lua:106: in function <...inetest_live/bin/../builtin/profiler/instrumentation.lua:100>
```

**Comment by Bastrabun** [comment] 2021-09-14 04:13
```
2021-09-14 06:00:45: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'water_life' in callback luaentity_Step(): ...ve1/5.4.1/Minetest_live/bin/../builtin/common/vector.lua:67: attempt to index local 'pos2' (a nil value)
2021-09-14 06:00:45: ERROR[Main]: stack traceback:
2021-09-14 06:00:45: ERROR[Main]: ...ve1/5.4.1/Minetest_live/bin/../builtin/common/vector.lua:67: in function 'direction'
2021-09-14 06:00:45: ERROR[Main]: /home/mtlive1/.minetest/mods/water_life/api.lua:447: in function 'get_yaw_to_object'
2021-09-14 06:00:45: ERROR[Main]: /home/mtlive1/.minetest/mods/water_life/behaviors.lua:1222: in function 'func'
2021-09-14 06:00:45: ERROR[Main]: /home/mtlive1/.minetest/mods/mobkit/init.lua:621: in function 'execute_queues'
2021-09-14 06:00:45: ERROR[Main]: /home/mtlive1/.minetest/mods/mobkit/init.lua:848: in function 'func'
2021-09-14 06:00:45: ERROR[Main]: ...inetest_live/bin/../builtin/profiler/instrumentation.lua:106: in function <...inetest_live/bin/../builtin/profiler/instrumentation.lua:100>
```

**Comment by berengma** [comment] 2021-09-19 09:57
All NIL checks are in place already. I would assume this is very likely to be a lag problem. 
It actually happens when a snake sees a player and starts it's warning behavior. You could try to
reproduce the error by nearing a snake and then quickly teleport away and see if it crashes.
If it is due to lag, there is not much I can do.

**Comment by Bastrabun** [comment] 2021-11-10 23:23
```
2021-11-10 02:00:35: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'water_life' in callback luaentity_Step(): ...ve1/5.4.1/Minetest_live/bin/../builtin/common/vector.lua:59: attempt to index local 'b' (a nil value)
2021-11-10 02:00:35: ERROR[Main]: stack traceback:
2021-11-10 02:00:35: ERROR[Main]: ...ve1/5.4.1/Minetest_live/bin/../builtin/common/vector.lua:59: in function 'dist2tgt'
2021-11-10 02:00:35: ERROR[Main]: /home/mtlive1/.minetest/mods/water_life/behaviors.lua:1226: in function 'func'
2021-11-10 02:00:35: ERROR[Main]: /home/mtlive1/.minetest/mods/mobkit/init.lua:621: in function 'execute_queues'
2021-11-10 02:00:35: ERROR[Main]: /home/mtlive1/.minetest/mods/mobkit/init.lua:848: in function 'func'
2021-11-10 02:00:35: ERROR[Main]: ...inetest_live/bin/../builtin/profiler/instrumentation.lua:106: in function <...inetest_live/bin/../builtin/profiler/instrumentation.lua:100>
```

For my reference 1028

**Comment by berengma** [comment] 2021-11-11 17:29
fixed, that had nothing to do with the other crashes.

**Comment by Bastrabun** [comment] 2021-11-18 02:24
Good news, we have a repro.

> 5.5.0-dev or 5.4.1, water_life 211111 and latest mobkit from content db, one MT instance a server, one a client

1. Replace water_life.dist2tgt with the following in api.lua line ~210

```
-- distance from self to target
function water_life.dist2tgt(self,tgt)
	core.log("action","self="..dump(self))
	core.log("action","tgt="..dump(tgt))
	local pos = mobkit.get_stand_pos(self)
	local tpos = tgt:get_pos()
	local thp = tgt:get_hp()
	core.log("action","pos="..dump(pos))
	core.log("action","tpos="..dump(tpos))
	core.log("action","thp="..dump(thp))
	return vector.distance(pos,tpos)
end
```

2. Enable water_life and mobkit on one instance of MT, lets call it MT1
3. Start the server on MT1
4. Start a client on the other instance, lets call it MT2
5. grant all, get some snakes and release them on MT2
6. Walk up to the snake on MT2 and match the hq_snake_warn conditions: dist > 4 and dist < self.view_range and not action
7. As soon as it warns, log out with MT2.

BOOM!

=> 

```
2021-11-18 03:05:21: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'water_life' in callback luaentity_Step(): ...5.5.0-dev/minetest-test/bin/../builtin/common/vector.lua:116: attempt to index local 'b' (a nil value)
2021-11-18 03:05:21: ERROR[Main]: stack traceback:
2021-11-18 03:05:21: ERROR[Main]: 	...5.5.0-dev/minetest-test/bin/../builtin/common/vector.lua:116: in function 'dist2tgt'
2021-11-18 03:05:21: ERROR[Main]: 	...0-dev/minetest-test/bin/../mods/water_life/behaviors.lua:1225: in function 'func'
2021-11-18 03:05:21: ERROR[Main]: 	...test/5.5.0-dev/minetest-test/bin/../mods/mobkit/init.lua:621: in function 'execute_queues'
2021-11-18 03:05:21: ERROR[Main]: 	...test/5.5.0-dev/minetest-test/bin/../mods/mobkit/init.lua:848: in function <...test/5.5.0-dev/minetest-test/bin/../mods/mobkit/init.lua:825>
```

But why? We obviously have a playerobject. Only that its get_pos() returns nil when logging out??

That's what the debug says:

```
2021-11-18 03:18:57: ACTION[Server]: pos={
	y = 18.510999679789,
	x = -316.15753173828,
	z = -411.00021362305
}
2021-11-18 03:18:57: ACTION[Server]: tpos=nil
2021-11-18 03:18:57: ACTION[Server]: thp=1
```

Try it yourself, you may take a couple of attempts to log out the right moment, but its a 100% repro over here by now. No lag or other mods involved but mtg, mobkit and water_life :)

**Comment by Gundul42** [comment] 2021-12-08 21:52
Ok I will test asap. We will see if this is really a water_life or a minetest issue.

**Comment by berengma** [comment] 2021-12-25 11:43
Thanks @Bastrabun ,
found the bug and fixed it.
closing

**Closed by berengma** 2021-12-25 11:43 UTC
